# Generated by Django 6.0.4 on 2026-06-21 21:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_reward_discount_percentage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bin',
            name='crowd_level',
            field=models.CharField(default='Low Crowd', max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='milestone_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='premium_unlocked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reward',
            name='icon_category',
            field=models.CharField(default='voucher', max_length=50),
        ),
        migrations.AddField(
            model_name='reward',
            name='subtitle',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='RedeemedReward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('redeemed_at', models.DateTimeField(auto_now_add=True)),
                ('reward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.reward')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
