# Generated by Django 6.0.4 on 2026-06-22 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_bin_crowd_level_profile_milestone_points_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='co2_saved_in_activity',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='bin',
            name='hardware_token',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='co2_saved',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='profile',
            name='fcm_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bin',
            name='lat',
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='bin',
            name='lng',
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='compound',
            name='lat',
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='compound',
            name='lng',
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
    ]
