# Generated by Django 6.0.4 on 2026-06-22 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_activity_co2_saved_in_activity_bin_hardware_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='date',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='bin',
            name='bin_id',
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
    ]
